name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # API Gateway
      - name: Build & Push API Gateway
        run: |
          docker build -t rockysaheb/ai-todo-api-gateway ./api-gateway
          docker push rockysaheb/ai-todo-api-gateway

      # Auth Service
      - name: Build & Push Auth Service
        run: |
          docker build -t rockysaheb/ai-todo-auth-service ./auth-service
          docker push rockysaheb/ai-todo-auth-service

      # Todo Service
      - name: Build & Push Todo Service
        run: |
          docker build -t rockysaheb/ai-todo-todo-service ./todo-service
          docker push rockysaheb/ai-todo-todo-service
